version: "3"

services:
  backend:
   build: .
   command: python portfolio/manage.py runserver 0.0.0.0:8080
   ports:
      - "8080:8080"
   depends_on:
      - db
   environment:
    - DATABASE_URL=postgres://main:develop@db:5432/portfolio
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: develop
      POSTGRES_DB: portfolio
    ports:
     - '5432:5432'